# Generated by Django 3.2.4 on 2021-06-29 11:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=50)),
                ('description', models.TextField(default=False, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('user_uuid', models.UUIDField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Сartridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField(null=True)),
                ('delivered_at', models.DateField(auto_now_add=True, null=True)),
                ('name', models.TextField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=65)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('url_wiki', models.URLField(blank=True, default='https://uk.wikipedia.org/')),
                ('description', models.TextField(max_length=1000, null=True)),
                ('available', models.BooleanField(default=False)),
                ('count', models.IntegerField(blank=True, default=0)),
                ('when_available', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('discount_available', models.DurationField(blank=True, default=datetime.timedelta(days=7))),
                ('price', models.DecimalField(blank=True, decimal_places=5, max_digits=5)),
                ('discount', models.FloatField(blank=True, default=1.0)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_55.category')),
            ],
        ),
        migrations.CreateModel(
            name='ClientInternet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('user_uuid', models.UUIDField(editable=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activation_date', models.DateField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('invoice', models.FileField(blank=True, upload_to='')),
                ('many_link', models.ManyToManyField(blank=True, to='lesson_55.Goods', verbose_name='You ordered these goods.')),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, null=True)),
                ('cartridge', models.ManyToManyField(to='lesson_55.Сartridge')),
            ],
            managers=[
                ('shop', django.db.models.manager.Manager()),
            ],
        ),
    ]
