# Generated by Django 3.2.4 on 2021-06-28 09:47

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('user_uuid', models.UUIDField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Сartridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField(null=True)),
                ('delivered_at', models.DateField(auto_now_add=True, null=True)),
                ('name', models.TextField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, null=True)),
                ('cartridge', models.ManyToManyField(to='lesson_55.Сartridge')),
            ],
            managers=[
                ('shop', django.db.models.manager.Manager()),
            ],
        ),
    ]
