# Generated by Django 3.2.4 on 2021-07-01 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_55', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinternet',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('9ef1af51-baa7-4a19-952d-12724408b6b8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
