# Generated by Django 3.2.4 on 2021-07-02 11:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_55', '0002_alter_clientinternet_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinternet',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('7fab4f76-05d4-4061-a414-0c4b44a4ecc4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
