# Generated by Django 3.2.4 on 2021-07-02 12:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_55', '0003_alter_clientinternet_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinternet',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('b7d7caa4-06c2-434e-bd51-30031b9ef5f8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
