# Generated by Django 3.2.4 on 2021-07-09 08:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_55', '0005_alter_clientinternet_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinternet',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('e2b5aa84-0398-4acd-9297-3caf2e8193fc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
