# Generated by Django 3.2.4 on 2021-07-09 08:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_55', '0006_alter_clientinternet_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinternet',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('74a898b9-ed19-4491-ab84-f1efcf9bdc75'), editable=False, primary_key=True, serialize=False),
        ),
    ]
