# Generated by Django 3.2.4 on 2021-07-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=65)),
                ('surname', models.CharField(blank=True, max_length=65)),
                ('age', models.IntegerField(blank=True)),
                ('company', models.TextField(blank=True, max_length=200)),
                ('salary', models.IntegerField(blank=True)),
            ],
        ),
    ]
