# Generated by Django 3.1.13 on 2021-07-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itvdn', '0002_auto_20210717_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
