# Generated by Django 3.1.13 on 2021-07-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_77', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts22',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
